
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nndapbgkyrdzluuosegf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uZGFwYmdreXJkemx1dW9zZWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTYzMDQsImV4cCI6MjA1ODY3MjMwNH0.wROxfSxfNKYDjZxCZjDXyIpmeuVvCeW961rGZQN1JW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to generate unique IDs for new entities
export const generateEntityId = (prefix: string) => {
  const randomNum = Math.floor(1000 + Math.random() * 9000);
  return `${prefix}-${randomNum}`;
};
